name: Feature Pipeline

on:
  push:
    branches: [ "main" ] # Triggers automatically on push to main branch
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub UI

jobs:
  ingest-features:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Specify your python version
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Run feature pipeline
        env:
          # Pulls the secret from your GitHub repository settings
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python feature_pipeline/daily_ingest.py
